spring:
  application:
    name: trading

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: ${DATASOURCE_DRIVER}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}